#!/bin/bash

set -e
THISDIR="$(dirname "$(readlink -f "$0")")"
source "${THISDIR}/common"

source '/root/.borg'

NUM_OUTPUTS=3
set +e
BORG_OUTPUT="$("${BORG}" \
  list \
  --prefix "${HOSTNAME}" \
  --list-format '{user:6}{TAB}{path}{size:8d}{NEWLINE}' \
  ${REPOSITORY} | \
  tail -n "${NUM_OUTPUTS}")"
SALL_GOOD=$?
set -e

if [[ $SALL_GOOD -eq 0 ]] ; then
  header 'Latest Backups'
  echo "${BORG_OUTPUT}"
else
  say_color "${COLOR_RED}" 'Unable to query backups'
  exit "${SALL_GOOD}"
fi

if [[ -r "${BORG_OUT}" ]] ; then
  echo -ne "${HEADER_COLOR}"
  "${EXTRACT}" "${BORG_OUT}"
  reset_color
fi
