#!/bin/bash

set -eu
set -o pipefail
THISDIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=./common
source "${THISDIR}/common"

# Vars
DASHCOUNT=0
TABLETIME=0
WEREDOINGITLIVE=0

INFILE="${1-}"
if [[ ! -e "${INFILE}" ]] ; then
  INFILE="/dev/stdin"
  if [[ ! "${INFILE}" == "-" ]] ; then
    # https://stackoverflow.com/questions/2990414/echo-that-outputs-to-stderr
    (>&2 echo "Reading from STDIN")
  fi
fi

# Functions

# get rid of some dumb shit
worth_displaying() {
  if [[ "${1}" =~ fingerprint ]] ; then
    return 1
  fi
  if [[ "${1}" =~ hunk ]] ; then
    return 1
  fi
  return 0
}

display_color() {
  if [[ "${1}" =~ size ]] ; then
    echo -ne "${BACKGROUND_NICE_BLUE}${BOLD}"
  elif [[ "${1}" =~ Archive ]] ; then
    echo -ne "${BACKGROUND_NICE_BLUE}${BOLD}"
  fi
  return
}

while IFS='' read -r line ; do
  if [[ "${line}" =~ ^--- ]] ; then
    ((DASHCOUNT++)) || true
    # we hit our first important thing
    WEREDOINGITLIVE=1
    case ${DASHCOUNT} in
      1) TABLETIME=1 ;;
      2) TABLETIME=0;;
      *) exit 0 ;;
    esac
    echo
    continue
  fi

  if [[ ${WEREDOINGITLIVE} == 1 ]] ; then
    if worth_displaying "${line}" ; then
      if has_delim "${line}" ':' &&  [[ ${TABLETIME} == 1 ]] ; then
        first="$(echo "${line}" | cut -d':' -f1)"
        rest="$(echo "${line}" | cut -d':' -f2- | sed 's/^[ ]\+//')"

        case "${line}" in
          Number*)
            # black magic
            rest="$(echo "${rest}" | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')"
            rest="\e[48;5;19m${rest}"
            ;;
          Archive)
            rest_color="${STYLE_NORMAL}"
            ;;
          Time*)
            rest_color="${STYLE_NORMAL}"
            ;;
          *)
            rest_color="${STYLE_BOLD}"
            ;;
        esac

        printf "%-${FIRST_COLUMN}s" "${first}"

        say_color "${rest_color}" "${rest}"
      else
        color="$(display_color "${line}")"
        say_color "${color}" "${line}" | tr ':' ' '
      fi
    fi
  fi
done < "${INFILE}"
