#!/bin/bash
# note: not to be run directly, shebang just for shellcheck
# vim: filetype=sh

THISDIR="$(dirname "$(readlink -f "$0")")"
export THISDIR
set +x

# Paths
export BORG_OUT='/tmp/borg.latest'
export EXTRACT="${THISDIR}/borg-extract"
export BORG="borg"

# Secret keys
BORG_KEYS='/root/.borg'
# shellcheck source=/dev/null
source "${BORG_KEYS}"


# Variables
USER="$(whoami)"
export USER
HOSTNAME="$(uname -n)"
export HOSTNAME

# Colors
export HEADER_COLOR="\e[48;5;237m"
export COLOR_COLUMN="\e[1m-"
export COLOR_YELLOW="\e[93m"
export COLOR_GREEN="\e[92m"
export COLOR_BLUE="\e[36m"  # actually cyan
export COLOR_RED="\e[41m"

# Styles
export STYLE_BOLD="\e[1m"

# Backgrounds
export BACKGROUND_NICE_BLUE="\e[48;5;31m"

# Resets
export RESET_TEXT="\e[0m"
export STYLE_NORMAL="\e[49m"

# Layout
export FIRST_COLUMN=30

# Backup configuration
export NUM_BACKUPS=3

# shellcheck source=./common
source "${BORG_KEYS}"

USER="$(whoami)"
HOSTNAME="$(uname -n)"

# somehowe, we can may this dynamic in the future.
export TARGET_WIDTH=20

display_column1() {
  printf " ${COLOR_COLUMN}- %-$((FIRST_COLUMN - 5))s${RESET_TEXT}" "${1}"
  echo -ne " ${RESET_TEXT}"
}

MULTIPLE_WHITESPACES='^[ ]\+'
function break_columns() {
  set +x
	WHITESPACE_BREAK="${WHITESPACE_BREAK:-MULTIPLE_WHITESPACES}"
  while read -r line ; do
    while read -ra columns ; do
      local columnParts=()
      columnParts+=("${columns}")

      for part in "${columnParts[@]}" ; do
        first="$(echo -e "${1}" | sed 's/\s${WHITESPACE_BREAK}//' "${part}")"
        local col1_width="$(echo "${first}" | wc -c)"
        printf "%-${FIRST_COLUMN}s" "${first}"
        printf "%-${padding}s" " "
        shift


        rest="$(echo "${line}" | sed 's/\s${WHITESPACE_BREAK}//' "${part}")"
        local col2_width="$(echo "${$*}" | wc -c)"
        padding=$((TARGET_WIDTH - col1_width - col2_width))
        printf "%-${FIRST_COLUMN}s" "${first}"
        printf "%-${padding}s" " "
        echo -e "${rest}"
				echo
      done
    done <<< "${1}"
  done
}

header_1() {
  set +x
  display_column1 "${1}"
	shift

	echo -e "$@"
}

say_color() {
  printf "%b%b%b\n" "${1}" "${2}" "${RESET_TEXT}"
}

header() {
  say_color "${HEADER_COLOR}" "${1}"
}

reset_color() {
  echo -ne "${RESET_TEXT}"
}

has_delim() {
  if [[ "${1}" =~ [$2] ]] ; then
    return 0
  fi
  return 1
}

trim_whitespace() {
  echo -e "${1}" | tr -d '[:space:]'
}
